services:
  app:
    build:
      context: .
      args:
        - "DEBUG=${DEBUG:-0}"
    volumes:
      - ./.env:/.env
      - ./serve/static:/static_root
      - ./serve/media:/media_root
    depends_on:
      - db
      - redis
    restart: always
    ports:
      - "${BIND_ADDR:-127.0.0.1:8000}:8000"

  tasks:
    build:
      context: .
      args:
        - "DEBUG=${DEBUG:-0}"
    volumes:
      - ./.env:/.env
    depends_on:
      - db
      - redis
    restart: always
    environment:
      - RUN_HUEY=1

  # radio:
  #   build:
  #     context: radio

  db:
    image: library/postgres:14-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      - POSTGRES_PASSWORD=postgres
      - "UMAMI_WEBSITE_ID=${UMAMI_WEBSITE_ID:-}"
      - "DOMAIN_NAME=${DOMAIN_NAME}"

  redis:
    image: library/redis:6-alpine
    restart: always
    volumes:
      - redis_data:/data

  # nchan:
  #   image: rookiezoe/nginx
  #   #restart: always
  #   ports:
  #     - "127.0.0.1:8888:80"

  umami:
    image: ghcr.io/mikecao/umami:postgresql-2575cbf
    restart: always
    ports:
      - "${UMAMI_BIND_ADDR:-127.0.0.1:3000}:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/umami
      - DATABASE_TYPE=postgresql
      # SECRET_KEY needs to be set in order to run this container
      - "HASH_SALT=${SECRET_KEY}"
      - "TZ=${TIMEZONE:-US/Eastern}"
    depends_on:
      - db

  logs:
    image: amir20/dozzle:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "${LOGS_BIND_ADDR:-127.0.0.1:8888}:8080"
    environment:
      - DOZZLE_TAILSIZE=2500
      - DOZZLE_NO_ANALYTICS=true
      - "TZ=${TIMEZONE:-US/Eastern}"

volumes:
  postgres_data:
  redis_data:
