services:
  app:
    restart: "no"
    volumes:
      - .:/app
    tty: true  # needed for tailwind --watch

  tasks:
    restart: "no"
    volumes:
      - .:/app

  db:
    restart: "no"
    ports:
      - "127.0.0.1:5432:5432"

  redis:
    restart: "no"
    ports:
      - "127.0.0.1:6379:6379"

  umami:
    restart: "no"

  logs:
    restart: "no"

  radio:
    restart: "no"
    volumes:
      - ./radio/entrypoint.sh:/entrypoint.sh
    ports:
      - "127.0.0.1:1234:1234"

  radio-uplink:
    restart: "no"
    volumes:
      - ./radio/entrypoint.sh:/entrypoint.sh

  radio-controller:
    restart: "no"
    ports:
      - "127.0.0.1:5000:8080"

  icecast:
    image: moul/icecast
    init: true  # for Icecast to shut down faster
    environment:
      - "ICECAST_HOSTNAME=${DOMAIN_NAME:-localhost}"
      - "TZ=${TIMEZONE:-US/Eastern}"
    ports:
      - 8080:8000
