x-service-dev-defaults: &service-dev-defaults
  restart: "no"
  # Disable autohealing for `docker compose run` during development
  labels:
    - "autoheal=false"

services:
  app:
    <<: *service-dev-defaults
    image: jewdotpizza/app:dev
    volumes:
      - .:/app
    tty: true  # needed for tailwind --watch
    ports:
      - "8000:8000"

  tasks:
    <<: *service-dev-defaults
    image: jewdotpizza/app:dev
    volumes:
      - .:/app

  radio:
    <<: *service-dev-defaults
    image: jewdotpizza/radio:dev
    depends_on:
      - icecast
    volumes:
      - ./backend/radio/jinja2/radio:/watch
      - ./radio/image/entrypoint.sh:/entrypoint.sh
      - ./radio/image/healthcheck.sh:/healthcheck.sh
    ports:
      - "127.0.0.1:1234:1234"

  nginx:
    <<: *service-dev-defaults
    image: jewdotpizza/nginx:dev
    volumes:
      - ./nginx/image/etc/nginx/templates:/etc/nginx/templates
      - ./nginx/image/etc/nginx/modules.conf:/etc/nginx/modules.conf
      - ./nginx/image/docker-entrypoint.d/25-jinja2-cli-config.sh:/docker-entrypoint.d/25-jinja2-cli-config.sh
      - ./nginx/image/docker-entrypoint.d/40-set-digitalocean-token.sh:/docker-entrypoint.d/40-set-digitalocean-token.sh
      - ./local-certificate-authority:/etc/local_ca
    environment:
      - "USE_LOCAL_CA=${NGINX_DEBUG_MODE_ONLY_USE_LOCAL_CERTIFICATE_AUTHORITY:-0}"
    ports:
      - "3000:3000"

  icecast:
    <<: *service-dev-defaults
    image: jewdotpizza/icecast:dev
    volumes:
      - ./icecast/icecast.xml.template:/etc/icecast.xml.template

  db:
    <<: *service-dev-defaults
    ports:
      - "127.0.0.1:5432:5432"

  redis:
    <<: *service-dev-defaults
    ports:
      - "127.0.0.1:6379:6379"

  umami:
    <<: *service-dev-defaults
    ports:
      - "127.0.0.1:3000:3000"

  logs:
    <<: *service-dev-defaults

  autoheal:
    <<: *service-dev-defaults
