services:
  app:
    restart: "no"
    volumes:
      - .:/app
    tty: true  # needed for tailwind --watch

  db:
    restart: "no"
    ports:
      - "127.0.0.1:5432:5432"

  redis:
    restart: "no"
    ports:
      - "127.0.0.1:6379:6379"

  umami:
    restart: "no"

  logs:
    restart: "no"

  icecast:
    image: moul/icecast
    init: true  # for Icecast to shut down faster
    environment:
      - "ICECAST_HOSTNAME=${DOMAIN_NAME:-localhost}"
    ports:
      - 8080:8000
