services:
  backend:
    restart: "no"
    volumes:
      - ./backend:/app
    ports:
      - 127.0.0.1:8000:8000
  frontend:
    restart: "no"
    volumes:
      - ./frontend:/app
  nginx:
    restart: "no"
    volumes:
      - ./nginx/image/etc/nginx/templates:/etc/nginx/templates
      - ./nginx/local-certificate-authority:/etc/local_ca
  db:
    restart: "no"
    ports:
      - "127.0.0.1:5432:5432"
  redis:
    restart: "no"
  analytics:
    restart: "no"
    ports:
      - "127.0.0.1:8001:8000"
  logs:
    restart: "no"
    ports:
      - "127.0.0.1:8002:8000"
