services:
  frontend-dev:
    image: library/node:16-alpine
    working_dir: /app/frontend-dev
    command: "/bin/sh -c '[ ! -d node_modules ] && npm install; npm run watch'"
    volumes:
      - .:/app
    tty: true  # Needed for tailwind --watch to work properly

  app:
    restart: "no"
    volumes:
      - ./backend:/app
      - ./entrypoint.sh:/entrypoint.sh
    ports:
      - "${LISTEN_PORT:-8000}:8000"
    depends_on:
      - frontend-dev

  db:
    restart: "no"
