services:
  app:
    image: jew_pizza_app
    volumes:
      - ./.env:/.env
      - ./media:/media_root
      - ./static:/static_root
    depends_on:
      - db
    restart: always
    build:
      context: .
    ports:
      - "127.0.0.1:${LISTEN_PORT:-8000}:8000"

  db:
    image: library/postgres:13-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: postgres

  tailwind-build:
    image: library/node:16-alpine
    working_dir: /app/tailwind
    command: "/bin/sh -c '[ ! -d node_modules ] && npm install; npm run build'"
    volumes:
      - .:/app
    profiles:
      - tools


volumes:
  postgres_data:
