services:
  app:
    image: dtcooper/jew_pizza_app:latest
    volumes:
      - ./.env:/.env
      - ./media:/app/media
      - ./static:/app/static
    depends_on:
      - db
    restart: always
    build:
      context: .
    ports:
      - "127.0.0.1:${LISTEN_PORT:-8000}:8000"

  db:
    image: library/postgres:13-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: postgres


volumes:
  postgres_data:
