services:
  app:
    build:
      context: .
      args:
        - "DEBUG=${DEBUG:-0}"
    volumes:
      - ./.env:/.env
      - ./serve/static:/static_root
      - ./serve/media:/media_root
    depends_on:
      - db
      - redis
    restart: always
    ports:
      - "127.0.0.1:${LISTEN_PORT:-8000}:8000"

  radio:
    build:
      context: radio

  db:
    image: library/postgres:13-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: postgres

  redis:
    image: library/redis:6-alpine
    restart: always
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
