x-service-dev-defaults: &service-dev-defaults
  restart: "no"
  # Disable autohealing for `docker compose run` during development
  labels:
    - "autoheal=false"

services:
  app:
    <<: *service-dev-defaults
    image: dtcooper/jewpizza-app:dev
    volumes:
      - .:/app
    tty: true  # needed for tailwind --watch
    ports:
      - "8000:8000"

  tasks:
    <<: *service-dev-defaults
    image: dtcooper/jewpizza-app:dev
    volumes:
      - .:/app

  radio:
    <<: *service-dev-defaults
    image: dtcooper/jewpizza-radio:dev
    depends_on:
      - icecast
    volumes:
      - ./backend/radio/jinja2/radio:/watch
      - ./radio/image/entrypoint.sh:/entrypoint.sh
    ports:
      - "127.0.0.1:1234:1234"

  sse:
    <<: *service-dev-defaults
    image: dtcooper/jewpizza-sse:dev
    volumes:
      - ./sse:/app
    ports:
      - "8001:8001"

  nginx:
    <<: *service-dev-defaults
    volumes:
      - ./nginx/image/etc/nginx/templates/jewpizza.conf.j2:/etc/nginx/templates/jewpizza.conf.j2

  icecast:
    <<: *service-dev-defaults

  db:
    <<: *service-dev-defaults
    ports:
      - "127.0.0.1:5432:5432"

  redis:
    <<: *service-dev-defaults
    ports:
      - "127.0.0.1:6379:6379"

  umami:
    <<: *service-dev-defaults

  logs:
    <<: *service-dev-defaults

  autoheal:
    <<: *service-dev-defaults
