services:
  app:
    restart: "no"
    volumes:
      - .:/app
    ports:
      - "${LISTEN_PORT:-8000}:8000"
    tty: true  # needed for tailwind --watch

  db:
    restart: "no"
    ports:
      - "127.0.0.1:5432:5432"

  redis:
    restart: "no"
    ports:
      - "127.0.0.1:6379:6379"

  # radio:
  #   depends_on:
  #     - icecast
  #   volumes:
  #     - ./radio/radio.liq:/etc/radio.liq

  # icecast:
  #   image: moul/icecast
  #   init: true  # for Icecast to shut down faster
  #   environment:
  #     - "ICECAST_HOSTNAME=${DOMAIN_NAME:-localhost}"
  #   ports:
  #     - 8080:8000
