x-service-defaults: &service-defaults
  restart: always

x-app-template: &app-template
  image: dtcooper/jewpizza-app:latest
  build:
    context: .
    dockerfile: backend/Dockerfile
    args:
      - "DEBUG=${DEBUG:-0}"
  volumes:
    - ./.env:/.env:ro
    - ./serve/static:/static_root
    - ./serve/media:/media_root
  depends_on:
    - db
    - redis

services:
  app:
    <<: *service-defaults
    <<: *app-template
    ports:
      - "${BIND_ADDR:-127.0.0.1:8000}:8000"
    environment:
      - "TZ=${TIMEZONE:-US/Eastern}"

  tasks:
    <<: *service-defaults
    <<: *app-template
    environment:
      - RUN_HUEY=1
      - "TZ=${TIMEZONE:-US/Eastern}"

  radio:
    <<: *service-defaults
    image: dtcooper/jewpizza-radio:latest
    build:
      context: radio
      args:
        - "DEBUG=${DEBUG:-0}"
    volumes:
      - ./.env:/.env:ro
    depends_on:
      - app
      - redis
    environment:
      - "TZ=${TIMEZONE:-US/Eastern}"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  sse:
    <<: *service-defaults
    image: dtcooper/jewpizza-sse:latest
    build:
      context: sse
      args:
        - "DEBUG=${DEBUG:-0}"
    volumes:
      - ./.env:/.env:ro
    depends_on:
      - redis
    ports:
      - "${SSE_BIND_ADDR:-127.0.0.1:8001}:8001"

  db:
    <<: *service-defaults
    image: library/postgres:14.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      - POSTGRES_PASSWORD=postgres
      - "TZ=${TIMEZONE:-US/Eastern}"

  redis:
    <<: *service-defaults
    image: library/redis:6.2-alpine
    volumes:
      - redis_data:/data
    environment:
      - "TZ=${TIMEZONE:-US/Eastern}"

  umami:
    <<: *service-defaults
    image: ghcr.io/mikecao/umami:postgresql-b756fcd
    depends_on:
      - db
    ports:
      - "${UMAMI_BIND_ADDR:-127.0.0.1:3000}:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/umami
      - DATABASE_TYPE=postgresql
      # SECRET_KEY needs to be set in order to run this container
      - "HASH_SALT=${SECRET_KEY:?SECRET_KEY needs to be set. See .env file.}"
      - "TZ=${TIMEZONE:-US/Eastern}"

  logs:
    <<: *service-defaults
    image: amir20/dozzle:v3.10.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "${LOGS_BIND_ADDR:-127.0.0.1:8888}:8080"
    environment:
      - DOZZLE_TAILSIZE=2500
      - DOZZLE_NO_ANALYTICS=true
      - "TZ=${TIMEZONE:-US/Eastern}"

volumes:
  postgres_data:
  redis_data:
