x-service-dev-defaults: &service-dev-defaults
  restart: "no"
  # Disable autohealing for `docker compose run` during development
  labels:
    - "autoheal=false"

services:
  app:
    <<: *service-dev-defaults
    image: dtcooper/jewpizza-app:dev
    volumes:
      - .:/app
    tty: true  # needed for tailwind --watch

  tasks:
    <<: *service-dev-defaults
    image: dtcooper/jewpizza-app:dev
    volumes:
      - .:/app

  radio:
    <<: *service-dev-defaults
    image: dtcooper/jewpizza-radio:dev
    depends_on:
      - icecast
    volumes:
      - ./backend/radio/jinja2/radio:/watch
      - ./radio/entrypoint.sh:/entrypoint.sh
    ports:
      - "127.0.0.1:1234:1234"

  sse:
    <<: *service-dev-defaults
    image: dtcooper/jewpizza-sse:dev
    volumes:
      - ./sse:/app

  db:
    <<: *service-dev-defaults
    ports:
      - "127.0.0.1:5432:5432"

  redis:
    <<: *service-dev-defaults
    ports:
      - "127.0.0.1:6379:6379"

  umami:
    <<: *service-dev-defaults

  logs:
    <<: *service-dev-defaults

  icecast:
    <<: *service-dev-defaults
    image: moul/icecast
    # TODO send SIGINT (https://docs.docker.com/compose/faq/#why-do-my-services-take-10-seconds-to-recreate-or-stop)
    init: true  # for Icecast to shut down faster
    environment:
      - "ICECAST_HOSTNAME=${DOMAIN_NAME:-localhost}"
      - "TZ=${TIMEZONE:-US/Eastern}"
    ports:
      - 8080:8000
