services:
  app:
    restart: "no"
    volumes:
      - .:/app
    ports:
      - "${LISTEN_PORT:-8000}:8000"
    tty: true  # needed for tailwind --watch

  db:
    restart: "no"
    ports:
      - "127.0.0.1:5432:5432"

  redis:
    restart: "no"
    ports:
      - "127.0.0.1:6379:6379"
