services:
  tailwind-dev:
    image: library/node:16-alpine
    working_dir: /app/tailwind-dev
    command: "/bin/sh -c '[ ! -d node_modules ] && npm install; npm run watch'"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    tty: true

  app:
    restart: "no"
    volumes:
      - .:/app
    ports:
      - "${LISTEN_PORT:-8000}:8000"

  db:
    restart: "no"
