services:
  tailwind-dev:
    image: library/node:16-alpine
    working_dir: /app/tailwind
    command: "/bin/sh -c '[ ! -d node_modules ] && npm install; npm run watch'"
    volumes:
      - .:/app

  app:
    restart: "no"
    volumes:
      - .:/app
    ports:
      - "${LISTEN_PORT:-8000}:8000"

  db:
    restart: "no"
