[tool.poetry]
name = "jew-pizza"
version = "0.0.1-dev"
description = ""
authors = ["David Cooper <david@jew.pizza>"]

[tool.poetry.dependencies]
python = "^3.10"
boto3 = "^1.20.46"
Brotli = "^1.0.9"
Django = "^4.0.2"
django-constance = "^2.8.0"
django-environ = "^0.8.1"
django-phonenumber-field = {extras = ["phonenumbers"], version = "^6.0.0"}
django-recurrence = "^1.11.1"
django-redis = "^5.2.0"
django-s3direct = "^2.0.0"
django-widget-tweaks = "^1.4.12"
gunicorn = "^20.1.0"
hiredis = "^2.0.0"
huey = "^2.4.3"
Jinja2 = "^3.0.3"
jinja-markdown = "^1.210911"
psycopg2 = "^2.9.3"
pytest = {version = "^6.2.5", optional = true}
pytest-cov = {version = "^3.0.0", optional = true}
pytest-django = {version = "^4.5.2", optional = true}
python-dateutil = "^2.8.2"
redis = "^4.1.2"
requests = "^2.27.1"
twilio = "^7.5.1"
Unidecode = "^1.3.2"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
django-extensions = "^3.1.5"
flake8 = "^4.0.1"
ipdb = "^0.13.9"
ipython = "^8.0.1"
isort = "^5.10.1"
lastversion = "^2.0.1"
pytest = "^6.2.5"
pytest-cov = "^3.0.0"
pytest-django = "^4.5.1"
watchdog = {extras = ["watchmedo"], version = "^2.1.6"}
whitenoise = "^5.3.0"
yq = "^2.13.0"

[tool.poetry.extras]
tests = ["pytest", "pytest-cov", "pytest-django"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ['py310']
exclude = '/migrations/'
experimental-string-processing = true

[tool.isort]
multi_line_output = 3
lines_after_imports = 2
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120
force_sort_within_sections = true
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'DJANGO', 'DJANGOTHIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER']
known_django = ['django']
known_djangothirdparty = ['constance', 'django_redis', 'environ', 'phonenumber_field', 'recurrence',
                          'widget_tweaks', 'huey.contrib', 's3direct']
skip = ['migrations']

[tool.pytest.ini_options]
addopts = '-s --cov=. --cov-report=term-missing'
python_files = 'tests.py'
cache_dir = '/tmp/.pytest_cache'
filterwarnings = [
    # Some warnings out of my control]
    "ignore:.*constance.apps.ConstanceConfig.*:django.utils.deprecation.RemovedInDjango41Warning",
    'ignore:::constance',
    'ignore:::markdown',
    'ignore:::recurrence',
    'ignore:::redis',
    'ignore:::s3direct',
]
