name: Deploy
description: Deploy jewpizza containers via SSH

inputs:
  host:
    description: SSH host
    required: true
  port:
    description: SSH port
    required: true
  username:
    description: SSH username
    required: true
  key:
    description: SSH key
    required: true
  fingerprint:
    description: SSH fingerprint
    required: true
  directory:
    description: SSH directory to deploy in
    required: true
  restart:
    description: Force restart of containers
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    -
        name: Deploy containers
        uses: appleboy/ssh-action@master
        env:
          RESTART: ${{ inputs.restart }}
        with:
          host: ${{ inputs.host }}
          port: ${{ inputs.port }}
          username: ${{ inputs.username }}
          key: ${{ inputs.key }}
          fingerprint: ${{ inputs.fingerprint }}
          script: |
            cd ${{ inputs.directory }}
            git pull --ff-only
            docker compose pull --quiet
            if [ "$RESTART" ]; then
              docker compose down --remove-orphans
            fi
            docker compose up --quiet-pull --remove-orphans --no-build --detach
            docker system prune --force
