name: Deploy
description: Deploy jewpizza containers via SSH

inputs:
  host:
    description: SSH host
    required: true
  port:
    description: SSH port
    required: false
    default: '22'
  username:
    description: SSH username
    required: true
  key:
    description: SSH key
    required: true
  fingerprint:
    description: SSH fingerprint
    required: true
  directory:
    description: SSH directory to deploy in
    required: true
  restart:
    description: Force restart of containers
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    -
        name: Deploy containers
        uses: appleboy/ssh-action@master
        env:
          DIRECTORY: ${{ inputs.directory }}
          RESTART: ${{ inputs.restart }}
          WORKFLOW_URL: ${{ github.server_url	}}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        with:
          host: ${{ inputs.host }}
          port: ${{ inputs.port }}
          username: ${{ inputs.username }}
          key: ${{ inputs.key }}
          fingerprint: ${{ inputs.fingerprint }}
          envs: DIRECTORY,RESTART,WORKFLOW_URL
          script_stop: true
          script: |
            cd "$DIRECTORY"
            git pull --ff-only
            docker compose pull --quiet
            if [ "$RESTART" ]; then
              docker compose down --remove-orphans
            fi
            docker compose up --quiet-pull --remove-orphans --no-build --detach
            docker compose exec redis sh -c "\
              DATE=\"\$(date -u +%FT%TZ)\"
              while ! nc -w 1 -z localhost 6379 ; do \
                echo 'waiting for redis...' ; \
                sleep 0.1 ; \
              done ; \
              redis-cli SET deploy::deployed-at \"\$DATE\" ; \
              redis-cli SET deploy::workflow-url '$WORKFLOW_URL' \
            "
            docker system prune --force --all
