inputs:
  container:
    description: 'Container name'
    required: true
  context:
    description: 'Docker context directory'
    required: false
    default: ''
  dockerfile:
    description: 'Dockerfile path'
    required: false
    default: ''
  username:
    description: 'Docker Hub username'
    required: false
    default: dtcooper
  token:
    description: 'Docker Hub access token'
    required: true

runs:
  using: "composite"
  steps:
    -
      name: Set variables
      id: vars
      run: |
        echo "::set-output name=sha::$(echo ${GITHUB_SHA} | cut -c1-8)"
        echo "::set-output name=container::${{ inputs.username }}/jewpizza-${{ inputs.container }}"
      shell: bash
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.token }}
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        platforms: linux/amd64
        build-args: GIT_REV=${{ steps.vars.outputs.sha }}
        context: ${{ inputs.context == '' && format('./{0}/', inputs.container) || inputs.context}}
        file: ${{ inputs.dockerfile == '' && format('./{0}/Dockerfile', inputs.container) || inputs.dockerfile}}
        tags: ${{ steps.vars.outputs.container }}:latest,${{ steps.vars.outputs.container }}:${{ steps.vars.outputs.sha }}
        cache-from: type=registry,ref=${{ steps.vars.outputs.container }}:buildcache
        cache-to: type=registry,ref=${{ steps.vars.outputs.container }}:buildcache,mode=max
