inputs:
  container:
    description: 'Container name'
    required: true
  context:
    description: 'Docker context directory'
    required: false
    default: ./
  dockerfile:
    description: 'Dockerfile path'
    required: true
  username:
    description: 'Docker Hub username'
    required: false
    default: dtcooper
  token:
    description: 'Docker Hub access token'
    required: true
  debug:
    description: 'Value for DEBUG build arg'
    required: false
    default: '0'

runs:
  using: "composite"
  steps:
    -
      name: Get short SHA
      id: sha
      run: echo "::set-output name=sha::$(echo ${GITHUB_SHA} | cut -c1-8)"
      shell: bash
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      if: ${{ inputs.debug == '1' }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.token }}
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        # Only build multi-arch for debug (dev) container since it's slow, we can deploy faster
        platforms: ${{ inputs.debug == '1' && 'linux/amd64,linux/arm64' || 'linux/amd64' }}
        build-args: |
          DEBUG=${{ inputs.debug }}
          GIT_REV=${{ steps.sha.outputs.sha }}
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        tags: "${{ inputs.username }}/jewpizza-${{ inputs.container }}:${{ inputs.debug == '1' && 'dev' || 'latest' }}\
               ${{ inputs.debug == '1' && '' || format(',{0}/jewpizza-{1}:{2}', inputs.username, inputs.container, steps.sha.outputs.sha) }}"
        cache-from: type=registry,ref=${{ inputs.username }}/jewpizza-${{ inputs.container }}:${{ inputs.debug == '1' && 'debug-' || '' }}buildcache
        cache-to: type=registry,ref=${{ inputs.username }}/jewpizza-${{ inputs.container }}:${{ inputs.debug == '1' && 'debug-' || '' }}buildcache,mode=max
