inputs:
  container:
    description: 'Container name'
    required: true
  context:
    description: 'Docker context directory'
    required: false
    default: ''
  dockerfile:
    description: 'Dockerfile path'
    required: false
    default: ''
  username:
    description: 'Docker Hub username'
    required: true
  password:
    description: 'Docker Hub password'
    required: true
  token:
    description: 'Docker Hub access token'
    required: true

runs:
  using: "composite"
  steps:
    -
      name: Set variables
      id: vars
      run: |
        echo "::set-output name=sha::$(echo ${GITHUB_SHA} | cut -c 1-8)"
        echo "::set-output name=repo::ghcr.io/${{ inputs.username }}/jewpizza-${{ inputs.container }}"
        echo "::set-output name=cache::ghcr.io/${{ inputs.username }}/jewpizza-cache:${{ inputs.container }}"
        echo "::set-output name=build-date::$(date -u +%FT%TZ)"
      shell: bash
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ inputs.username }}
        password: ${{ inputs.token }}
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        platforms: linux/amd64
        build-args: |
          GIT_REV=${{ steps.vars.outputs.sha }}
          BUILD_DATE=${{ steps.vars.outputs.build-date }}
          DEBUG=0
        context: ${{ inputs.context == '' && format('./{0}/', inputs.container) || inputs.context}}
        file: ${{ inputs.dockerfile == '' && format('./{0}/Dockerfile', inputs.container) || inputs.dockerfile}}
        tags: |
          ${{ steps.vars.outputs.repo }}:latest
          ${{ steps.vars.outputs.repo }}:${{ steps.vars.outputs.sha }}
        cache-from: type=registry,ref=${{ steps.vars.outputs.cache }}
        cache-to: type=registry,ref=${{ steps.vars.outputs.cache }},mode=max
