inputs:
  container:
    description: 'Container name'
    required: true
  context:
    description: 'Docker context directory'
    required: true
  dockerfile:
    description: 'Dockerfile path'
    required: true
  username:
    description: 'Docker Hub username'
    required: true
  token:
    description: 'Docker Hub access token'
    required: true

runs:
  using: "composite"
  steps:
    -
      name: Get short SHA
      id: sha
      run: echo "::set-output name=sha::$(echo ${GITHUB_SHA} | cut -c1-8)"
      shell: bash
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.token }}
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        build-args: GIT_REV=${{ steps.sha.outputs.sha }}
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        tags: ${{ inputs.username }}/jewpizza-${{ inputs.container }}:latest,${{ inputs.username }}/jewpizza-${{ inputs.container }}:${{ steps.sha.outputs.sha }}
        cache-from: type=registry,ref=${{ inputs.username }}/jewpizza-${{ inputs.container }}:buildcache
        cache-to: type=registry,ref=${{ inputs.username }}/jewpizza-${{ inputs.container }}:buildcache,mode=max
