name: Deploy

on:
  workflow_dispatch:
      restart:
        description: Force restart of containers
        required: false
        default: ''

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    env:
      SSH_DIRECTORY: jewpizza
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Deploy containers
        uses: ./.github/actions/deploy
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          fingerprint: ${{ secrets.SSH_FINGERPRINT }}
          directory: ${{ env.SSH_DIRECTORY }}
          restart: ${{ github.event.inputs.restart }}
