name: Docker Containers

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    name: Build and deploy docker containers
    steps:
      -
        name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      -
        name: Get short SHA
        id: slug
        run: echo "::set-output name=sha::$(echo ${GITHUB_SHA} | cut -c1-7)"

      -
        name: Check out repository
        uses: actions/checkout@v2

      -
        name: Build app container
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          image_tag: ${{ steps.slug.outputs.sha }},latest
          image_name: dtcooper/jewpizza-app
          build_extra_args: "--build-arg=GIT_REV=${{ steps.slug.outputs.sha }}"
          dockerfile: backend/Dockerfile

      -
        name: Build radio container
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          image_tag: ${{ steps.slug.outputs.sha }},latest
          image_name: dtcooper/jewpizza-radio
          context: ./radio/

      -
        name: Build sse container
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          image_tag: ${{ steps.slug.outputs.sha }},latest
          image_name: dtcooper/jewpizza-sse
          context: ./sse/

      -
        name: Deploy containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          fingerprint: ${{ secrets.SSH_FINGERPRINT }}
          script: |
            cd ${{ secrets.SSH_DEPLOY_DIRECTORY }}
            SHOULD_DEPLOY=
            if docker compose ps --services --filter "status=running" | grep -q '^app$'; then
              if [ "$(docker compose exec app poetry run ./manage.py constance get AUTO_DEPLOY)" = True ]; then
                SHOULD_DEPLOY=1
              fi
            else
              SHOULD_DEPLOY=1
            fi
            if [ "$SHOULD_DEPLOY" ]; then
              git pull --ff-only
              docker compose pull
              docker compose up --remove-orphans -d
              docker system prune -f
            else
              echo "Deploy disabled by constance config (AUTO_DEPLOY = False)"
            fi
