name: docker-build

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Get short SHA
        id: slug
        run: echo "::set-output name=sha::$(echo ${GITHUB_SHA} | cut -c1-7)"

      -
        name: Check out repository
        uses: actions/checkout@v2

      -
        name: Build containers and push to Docker Hub
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          compose_file: docker-compose.yml
          image_tag: ${{ steps.slug.outputs.sha }},latest
          build_extra_args: "--build-arg=GIT_REV=${{ steps.slug.outputs.sha }}"
