name: docker-build

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Get short SHA
        id: slug
        run: echo "::set-output name=sha::$(echo ${GITHUB_SHA} | cut -c1-7)"

      -
        name: Check out repository
        uses: actions/checkout@v2

      -
        name: Build containers and push to Docker Hub
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          compose_file: docker-compose.yml
          image_tag: ${{ steps.slug.outputs.sha }},latest
          build_extra_args: "--build-arg=GIT_REV=${{ steps.slug.outputs.sha }}"

      -
        name: Update dev deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          fingerprint: ${{ secrets.SSH_FINGERPRINT }}
          script_stop: true
          script: |
            cd dev.jew.pizza
            SHOULD_DEPLOY=
            if docker compose ps --services --filter "status=running" | grep -q '^app$'; then
              if [ "$(docker compose exec app poetry run ./manage.py constance get AUTO_DEPLOY)" = True ]; then
                SHOULD_DEPLOY=1
              fi
            else
              SHOULD_DEPLOY=1
            fi
            if [ "$SHOULD_DEPLOY" ]; then
              git pull --ff-only
              docker compose pull
              docker compose up --remove-orphans -d
              docker system prune -f
            else
              echo "Deploy disabled by constance config (AUTO_DEPLOY = False)"
            fi
