name: Build (Dev)

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: main-dev
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build dev container
    strategy:
      matrix:
        container: [app, icecast, nginx, radio]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build container
        uses: ./.github/actions/docker-build-push
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          container: ${{ matrix.container }}
          dev: '1'
